//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.notes = new HashSet<Note>();
            this.sessions = new HashSet<Session>();
        }
    
        public int CardID { get; set; }
        public string PatientName { get; set; }
        public int PatientAge { get; set; }
        public string Sex { get; set; }
        public string Note { get; set; }
        public byte[] IsAgain { get; set; }
    
        public virtual ICollection<Note> notes { get; set; }
        public virtual ICollection<Session> sessions { get; set; }
    }
}
