//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public Diagnosis()
        {
            this.sessions = new HashSet<Session>();
        }
    
        public int DiagnosisID { get; private set; }
        public string Description { get; set; }
        public int GroupOwnerID { get; set; }
    
        public virtual Group group { get; set; }
        public virtual ICollection<Session> sessions { get; set; }
    }
}
