//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.diagnosis = new HashSet<Diagnosis>();
            this.groups1 = new HashSet<Group>();
        }
    
        public int GroupID { get; private set; }
        public string Name { get; set; }
        public int GroupOwnerID { get; set; }
    
        public virtual ICollection<Diagnosis> diagnosis { get; set; }
        public virtual ICollection<Group> groups1 { get; set; }
        public virtual Group group1 { get; set; }
    }
}
