//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; private set; }
        public int UserID { get; set; }
        public int CardID { get; set; }
        public bool IsHidden { get; set; }
        public System.DateTime Date { get; set; }
        public string NoteText { get; set; }
    
        public virtual Card card { get; set; }
        public virtual User user { get; set; }
    }
}
