//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.notes = new HashSet<Note>();
        }
    
        public int UserID { get; private set; }
        public string Name { get; set; }
        public int AccessLevel { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Note> notes { get; set; }
    }
}
